### PR TITLE
fix: update storage utilized for object overwrites

### LINKED ISSUE #28: Update storage utilized with delta values on object PUT overwrites
When an object is overwritten only the difference needs to be updated, as in deltaSize = newSize - oldSize

### PR DESCRIPTION
**Pull request by rahulreddy**
When an object is overwritten with new data the storage utilized counter should reflect only the total change in the size (storage + ( new size - old size ))

Fix #28

### CODE REVIEW

File: lib/UtapiClient.js [hunk 1]
```diff
@@ -652,20 +652,23 @@ export default class UtapiClient {
...
+        const storageUtilizedDelta = objectSize - prevObjectSize;
         this.log.trace('pushing metric',
             { method: 'UtapiClient.pushMetricPutObject', bucket, timestamp });
         // update counters
         return this.ds.batch([
             ['incrby', genBucketKey(bucket, 'storageUtilizedCounter'),
-                objectSize],
+                storageUtilizedDelta],
             ['incrby', genBucketKey(bucket, 'incomingBytesCounter'),
                 objectSize],
```
Comment (alexandre-merle) [inline lib/UtapiClient.js]: you don't need to do the same here ?

**Comment by alexandre-merle** [comment]
one comment, LGTM :+1:

**Comment by nicolas2bert** [comment]
👍

File: lib/UtapiClient.js (hunk 1 above)
Comment (rahulreddy) [inline lib/UtapiClient.js]: Regardless of whether the object is being overwritten, there will be bytes transferred over the network and incoming bytes is capturing just that.
