### PR TITLE
fix: operations counters

### LINKED ISSUE #44: operations count does not increment on multiple actions
For example, doing 5 object PUTs we expect the operations count in the response to be 5, instead it is 1.

### PR DESCRIPTION
**Pull request by rahulreddy**
PR #37 of reducing the time precision introduced a bug which made
calculating operations incorrectly. As the code no longer adds multiple
members for the same timestamp (counters are updated for the normalized
timestamp), the solution has been simplified as follows

- All keys which hold operations counters (put object, create bucket etc.)
  use string keys instead of sorted sets

- INCR cmd is issued for the normalized timestamp on key on every push
  metric

- Total number of operations between start and end timestamps is the sum
  of counts held by the keys that fall between the two timestamps

- As sorted sets are no longer used for operations, there is no need for
  global counters for these keys, hence they are removed

- The only metrics which use sorted sets are the ones holding bucket state
  data - storage utilized and number of objects. Sorted sets are the best
  candidates for finding the nearest neighbor values

Fix #44

### CODE REVIEW

**Comment by rahulreddy** [comment]
This PR has commits from other PRs. Please review **fix: operations counters** commit only.

File: lib/Buckets.js [hunk 1]
```diff
@@ -150,15 +137,13 @@ export default class Buckets {
...
                     's3:HeadBucket': 0,
                     's3:HeadObject': 0,
                 },
             };
 
-            // last 8 are results of storageUtilized, numberOfObjects,
-            // incomingBytes and outgoingBytes
-            const absolutes = res.splice(-8);
+            // last 4 are results of storageUtilized, numberOfObjects,
+            const absolutes = res.splice(-4);
```
Comment (LaurenSpiegel) [inline lib/Buckets.js]: I would do two slices.

Comment (rahulreddy) [inline lib/Buckets.js]: I made the change, I know that it enhances code readability.

File: lib/Buckets.js [hunk 2]
```diff
@@ -212,12 +183,15 @@ export default class Buckets {
...
-                } else if (Array.isArray(item[1])) {
-                    // convert strings to numbers for comparision
+                } else {
                     const m = getMetricFromKey(key, bucket);
-                    // count is enough as it represents the delta of the
-                    // metric between the two timestamps
-                    bucketRes.operations[`s3:${m}`] += item[1].length || 0;
+                    let count = parseInt(item[1], 10);
+                    count = Number.isNaN(count) ? 0 : count;
+                    if (m === 'incomingBytes' || m === 'outgoingBytes') {
```
Comment (LaurenSpiegel) [inline lib/Buckets.js]: why aren't these just called s3:incomingBytes as well?

File: lib/UtapiClient.js [hunk 3]
```diff
@@ -861,69 +656,32 @@ export default class UtapiClient {
...
             }
+            cmds.push(
+                ['zremrangebyscore',
+                    genBucketStateKey(bucket, 'storageUtilized'),
+                    timestamp, timestamp],
+                ['zadd', genBucketStateKey(bucket, 'storageUtilized'),
+                    timestamp, actionCounter]);
 
-            // incoming bytes counter
+            // number of objects counter
```
Comment (LaurenSpiegel) [inline lib/UtapiClient.js]: Is this correct?  You have number of objects counter above.

File: lib/Buckets.js (hunk 2 above)
Comment (rahulreddy) [inline lib/Buckets.js]: because that's the key we are using in our responses. The `s3:` prefix was added only for the api operations list (s3:putObject, s3:getObject etc.)

File: lib/UtapiClient.js (hunk 3 above)
Comment (rahulreddy) [inline lib/UtapiClient.js]: incoming bytes has been removed, so I updated the comment. Storage utilized is line 650

File: lib/UtapiClient.js [hunk 4]
```diff
@@ -409,67 +319,40 @@ export default class UtapiClient {
...
             ['incr', genBucketCounter(bucket, 'numberOfObjectsCounter')],
-            ['incr',
-                genBucketCounter(bucket, 'completeMultipartUploadCounter')],
+            ['incr', genBucketKey(bucket, 'completeMultipartUpload',
+                timestamp)],
         ], (err, results) => {
-            // number of objects counter
             if (err) {
                 log.error('error incrementing counter for push metric', {
                     method: 'UtapiClient.pushMetricPutObject',
```
Comment (alexandre-merle) [inline lib/UtapiClient.js]: pushMetricCompleteMultipartUpload

Comment (rahulreddy) [inline lib/UtapiClient.js]: Fixed.
