### PR TITLE
FIX: Handle negative counter values

### LINKED ISSUE #107: Handle updates from negative counters on Redis disconnect
Context: While the connection to the Redis server is interrupted, PUT operations are made. Thus `storageUtilized` and `numberOfObjects` metrics are not updated as expected.

The Redis server then reestablishes a connection, and DELETE operations are made. But because metrics were not previously updated for the PUT operations, `storageUtilized` and `numberOfObjects` counters are updated to a negative value. Finally, a PUT operation is made and updates the stateful key values for `storageUtilized` and `numberOfObjects` based on the negative counter values. This causes metrics for the Sorted Set keys to be a negative value.

Duplicate of #105

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Fix #107
* Allow global counter keys to be < 0
* Reset Sorted Set keys as though the bucket
  were empty if the global counter is < 0

### CODE REVIEW

File: tests/functional/testUtapiClient.js [hunk 1]
```diff
@@ -1,37 +1,94 @@
...
+        datastore.get(item, (err, res) => {
             if (err) {
                 return next(err);
             }
-            const metric = getMetricFromKey(item, bucket)
-                .replace(':counter', '');
-            assert.equal(res, 0, `${metric} must be 0`);
+            let metric = getMetricFromStateKey(item, bucket);
+            metric = metric.replace(':counter', '');
+            assert.equal(res, valueObj[metric],
```
Comment (rahulreddy) [inline tests/functional/testUtapiClient.js]: Please change this to use `assert.strictEqual` here. Your tests are actually comparing a string to a number.
Pasting a console.log here
```
res [ '9' ] valueObj[metric] 9
res [ '1' ] valueObj[metric] 1
```

File: tests/functional/testUtapiClient.js [hunk 2]
```diff
@@ -1,37 +1,94 @@
...
+                `${metric} must be ${valueObj[metric]}`);
             return next();
         }), cb);
 }
 
+function _assertStateKeys(bucket, valueObj, cb) {
+    const stateKeys = getBucketStateKeys(testBucket);
+    return mapSeries(stateKeys, (item, next) =>
```
Comment (rahulreddy) [inline tests/functional/testUtapiClient.js]: Why not just use the map, it would execute the queries in parallel.

File: src/lib/UtapiClient.js [hunk 3]
```diff
@@ -255,7 +255,8 @@ export default class UtapiClient {
             }
             // storage utilized counter
             const actionErr = results[0][0];
-            const actionCounter = results[0][1];
+            const actionCounter = results[0][1] < 0 ? objectSize :
```
Comment (rahulreddy) [inline src/lib/UtapiClient.js]: Please add a one-liner comment explaining why objectSize was used vs 0.

File: tests/functional/testUtapiClient.js [hunk 4]
```diff
@@ -49,6 +106,53 @@ describe('Counters', () => {
...
             next => utapiClient.pushMetricCreateBucket(reqUid, testBucket,
                 next),
-        ], () => _assertCounters(testBucket, done));
+        ], () => _assertCounters(testBucket, {
+            storageUtilized: 0,
+            numberOfObjects: 0,
+        }, done));
     });
+
+    it('should update counters to correct values < 0: putObject', done =>
```
Comment (rahulreddy) [inline tests/functional/testUtapiClient.js]: Since we are technically not updating counters but actually recording the counter for a timestamp, the test description should reflect that.

File: tests/functional/testUtapiClient.js [hunk 5]
```diff
@@ -1,37 +1,94 @@
...
+        next => {
+            if (operation === 'PutObject') {
+                return utapiClient.pushMetricPutObject(reqUid, testBucket, 9,
+                    null, next);
+            }
+            if (operation === 'CopyObject') {
+                return utapiClient.pushMetricCopyObject(reqUid, testBucket, 9,
+                    null, next);
+            }
+            return utapiClient.pushMetricUploadPart(reqUid, testBucket, 9,
```
Comment (jonathan-gramain) [inline tests/functional/testUtapiClient.js]: Could be clearer to check the operation type here too (with a switch?)

File: tests/functional/testUtapiClient.js [hunk 6]
```diff
@@ -49,6 +106,53 @@ describe('Counters', () => {
...
+        _checkMissingOperations(_assertCounters, 'CopyObject', counterKeyValues,
+            done));
+
+    it('should update counters to correct values < 0: completeMPU', done =>
+        _checkMissingOperations(_assertCounters, 'CompleteMultipartUpload',
+            counterKeyValues, done));
+
+    it('should update counters to correct values < 0: uploadPart', done =>
+        // Uploading a part does not increment numberOfObjects value.
+        _checkMissingOperations(_assertCounters, null,
```
Comment (jonathan-gramain) [inline tests/functional/testUtapiClient.js]: related to my previous comment: I think passing the operation name here would be more readable.

Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Thank you. I had an internal debate about this, so I will update as you suggest. :)

File: src/lib/schema.js [hunk 7]
```diff
@@ -83,6 +83,17 @@ export function getMetricFromKey(key, bucket) {
...
 
 /**
+* Returns metric from a state key
+* @param {string} key - schema key
+* @param {string} bucket - bucket name
+* @return {string} metric - S3 metric
+*/
+export function getMetricFromStateKey(key, bucket) {
+    // s3:buckets:foo:storageUtilized
+    return key.slice(11).replace(`${bucket}:`, '');
```
Comment (jonathan-gramain) [inline src/lib/schema.js]: Could return what is after the last colon, otherwise if that does not work, you may use `'s3:buckets'.length` instead of the hard-coded 11 after checking that's how the string starts (unless there's a potential big performance impact doing this).

Comment (bennettbuchanan) [inline src/lib/schema.js]: Updated. That's much more intuitive—I will eventually update those other methods using the same pattern. Thanks!

File: tests/functional/testUtapiClient.js (hunk 6 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: tests/functional/testUtapiClient.js (hunk 5 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: src/lib/UtapiClient.js (hunk 3 above)
Comment (bennettbuchanan) [inline src/lib/UtapiClient.js]: I've done this for each pushMetric method.

File: tests/functional/testUtapiClient.js (hunk 2 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: tests/functional/testUtapiClient.js (hunk 1 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Now checking for integer values in both assertions.

**Comment by bennettbuchanan** [comment]
http://ci.ironmann.io/gh/scality/Integration/9502

File: tests/functional/testUtapiClient.js (hunk 4 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: src/lib/schema.js [hunk 8]
```diff
@@ -83,6 +83,17 @@ export function getMetricFromKey(key, bucket) {
...
 
 /**
+* Returns metric from a state key
+* @param {string} key - schema key
+* @param {string} bucket - bucket name
+* @return {string} metric - S3 metric
+*/
+export function getMetricFromStateKey(key, bucket) {
+    // s3:buckets:foo:storageUtilized
+    return key.slice('s3:buckets:'.length).replace(`${bucket}:`, '');
```
Comment (rahulreddy) [inline src/lib/schema.js]: One last change, this can be a constant up top as it's static.

Comment (bennettbuchanan) [inline src/lib/schema.js]: As in, no need for the method?

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
@ironman-machine try

File: src/lib/schema.js [hunk 9]
```diff
@@ -39,6 +39,12 @@ const bucketKeys = {
     outgoingBytes: (b, t) => `s3:buckets:${t}:${b}:outgoingBytes`,
 };
 
+const metric = {
+    stateKey: (k, b) => k.slice('s3:buckets:'.length).replace(`${b}:`, ''),
+    timestampKey: (k, b) =>
+        k.slice('s3:buckets:0000000000000:'.length).replace(`${b}:`, ''),
```
Comment (jonathan-gramain) [inline src/lib/schema.js]: I fear this is a bit fragile to rely on the number of digits in a timestamp. Since fields look to be delimited by colons, and since you must know how many fields you want to truncate, can you instead slice up to the number of fields you want to remove, where they are separated by colons? You can consider using a regexp if that makes the thing simpler.

File: tests/functional/testUtapiClient.js [hunk 10]
```diff
@@ -1,37 +1,90 @@
...
+
+datastore.setClient(redis);
 utapiClient.setDataStore(datastore);
 
-function _assertCounters(bucket, cb) {
+function _assertCounters(bucket, valueObj, cb) {
     const counters = getBucketCounters(testBucket);
-    return mapSeries(counters, (item, next) =>
-        memBackend.get(item, (err, res) => {
+    return map(counters, (item, next) =>
```
Comment (jonathan-gramain) [inline tests/functional/testUtapiClient.js]: minor: `next` could be called simply `cb` or `done`, because calls are neither ordered nor serialized (anymore).

File: tests/functional/testUtapiClient.js [hunk 11]
```diff
@@ -1,37 +1,90 @@
...
+            metric = metric.replace(':counter', '');
+            assert.strictEqual(parseInt(res, 10), valueObj[metric],
+                `${metric} must be ${valueObj[metric]}`);
+            return next();
+        }), cb);
+}
+
+function _assertStateKeys(bucket, valueObj, cb) {
+    const stateKeys = getBucketStateKeys(testBucket);
+    return map(stateKeys, (item, next) =>
```
Comment (jonathan-gramain) [inline tests/functional/testUtapiClient.js]: same here

File: src/lib/UtapiClient.js [hunk 12]
```diff
@@ -339,7 +341,8 @@ export default class UtapiClient {
             }
             // number of objects counter
             const actionErr = results[0][0];
-            const actionCounter = results[0][1];
+            // If < 0, record numberOfObjects as though bucket were empty.
```
Comment (jonathan-gramain) [inline src/lib/UtapiClient.js]: I have to admit the logic of handling negative results escapes me, but I trust it's the right thing :)

File: src/lib/schema.js (hunk 9 above)
Comment (rahulreddy) [inline src/lib/schema.js]: I agree, slicing it up is more predictable.

**Comment by bennettbuchanan** [comment]
@ironman-machine try

File: src/lib/UtapiClient.js (hunk 12 above)
Comment (bennettbuchanan) [inline src/lib/UtapiClient.js]: If UtapiReplay does not update previously unsuccessful metrics when a 15 minute interval occurs, there is the possibility of the metrics showing a negative value for that interval. Of course, it doesn't ever make sense for `storageUtilized` or `numberOfObjects` to be recorded as a negative value.

This addresses that possibility by instead recording a value of `0` for that time period, essentially allowing some flexibility. The design is such that eventually these metrics will be updated appropriately.

File: tests/functional/testUtapiClient.js (hunk 11 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: tests/functional/testUtapiClient.js (hunk 10 above)
Comment (bennettbuchanan) [inline tests/functional/testUtapiClient.js]: Updated.

File: src/lib/schema.js (hunk 9 above)
Comment (bennettbuchanan) [inline src/lib/schema.js]: Thanks, that's much better. 😄

**Comment by bennettbuchanan** [comment]
@ironman-machine try

**Comment by bennettbuchanan** [comment]
e2e passed
